version: '3.1'
services:
  redmine:
    image: redmine
    restart:always
    ports:
      -	8090:3000
    environment:
      REDMINE_DB_MYSQL:	db
      REDMINE_DB_PASSWORD: pass
      REDMINE_SECRET_KEY_BASE: key
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: redmine

